 <?php if ($this->pageCount): ?>
     <div>
         <ul class="pagination">
             <!-- Previous page link -->
             <?php if (isset($this->previous)): ?>
                 <li>
                     <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>"><i class="material-icons">chevron_left</i></a>
                 </li>

             <?php else: ?>
                 <li class="disabled">
                     <a href="#"><i class="material-icons">chevron_left</i></a>
                 </li>
             <?php endif; ?>

             <!-- Numbered page links -->
             <?php foreach ($this->pagesInRange as $page): ?>
                 <?php if ($page != $this->current): ?>
                     <li>
                         <a class="waves-effect" href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?>">
                             <?php echo $page; ?>
                         </a>
                     </li>
                 <?php else: ?>
                     <li class="active">
                         <a href="#" class="waves-effect"><?php echo $page; ?></a>
                     </li>
                 <?php endif; ?>
             <?php endforeach; ?>

             <!-- Next page link -->
             <?php if (isset($this->next)): ?>
                 <li>
                     <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>"><i class="material-icons">chevron_right</i></a>
                 </li>
             <?php else: ?>
                 <li class="disabled">
                      <a href="#"><i class="material-icons">chevron_right</i></a>
                 </li>
             <?php endif; ?>
         </ul>
     </div>
 <?php endif; ?>