<br /><br /><br />


<div id="article_prototype_grid">

  <div class="col-md-3">
    <div class="grid_syst teal">
        <img src="sl/1.jpg" height="70%" width="100%">
        <h5 class="text-center">titre de l'article</h5>
        <p class="" style="float: left; margin-right:10px;">article hint content...</p>
        <a href="#" class="btn btn-primary red btn-sm">read more</a>
    </div>
  </div>

  <div class="col-md-3">
    <div class="grid_syst teal">
       <img src="sl/2.jpg" height="70%" width="100%">
       <h5 class="text-center">titre de l'article</h5>
       <p class="" style="float: left; margin-right:10px;">article hint content...</p>
       <a href="#" class="btn btn-primary red btn-sm">read more</a>
    </div>
  </div>

  <div class="col-md-3">
    <div class="grid_syst teal">
        <img src="sl/3.jpg" height="70%" width="100%">
        <h5 class="text-center">titre de l'article</h5>
        <p class="" style="float: left; margin-right:10px;">article hint content...</p>
        <a href="#" class="btn btn-primary red btn-sm">read more</a>
    </div>
  </div>

  <div class="col-md-3">
    <div class="grid_syst teal">
        <img src="sl/4.jpg" height="70%" width="100%">
        <h5 class="text-center">titre de l'article</h5>
        <p class="" style="float: left; margin-right:10px;">article hint content...</p>
        <a href="#" class="btn btn-primary red btn-sm">read more</a>
    </div>
  </div>

</div>
<br/><br/>

