<?php
use Zend\Session\Container;
echo $this->doctype ();
?>

<!DOCTYPE html>
<html lang="en">
<head>
      <?php echo $this->headTitle('Lmpe')->setSeparator(' - ')->setAutoEscape(false)?>
      <?php echo $this->headMeta()
      ->appendName( 'viewport', 'width=device-width, initial-scale=1.0' )
      ->appendHttpEquiv( 'X-UA-Compatible', 'IE=edge' )?>

			
      <?php 
      
      
      
      echo $this->headLink()
      ->prependStylesheet( $this->basePath('css/bootstrap.min.css' ))
      ->prependStylesheet($this->basePath( 'css/normalize.css' ))
      ->prependStylesheet($this->basePath( 'css/demo.css' ))
      ->prependStylesheet($this->basePath( 'css/dragdealer.css' ))
      ->prependStylesheet($this->basePath( 'w3/css/component.css.css' ))
      ->prependStylesheet($this->basePath( 'w3/w3.css' ))
      ->prependStylesheet( $this->basePath('css/style.css' ));

      echo $this->headScript()
      ->prependFile( $this->basePath( 'js/jquery.js' ))
      ->prependFile( $this->basePath( 'js/jquery.min.js' ))
      ->prependFile( $this->basePath( 'js/bootstrap.min.js' ))
      ->prependFile( $this->basePath( 'js/modernizr.custom.js.js' ))
      ->prependFile( $this->basePath( 'js/dragdealer.js' ))
      ->prependFile( $this->basePath( 'js/classie.js' ))
      ->prependFile( $this->basePath( 'js/dragslideshow.js' ))
      ->prependFile( $this->basePath( 'js/script.js' ))
      ->prependFile( $this->basePath( 'js/googlemaps.js' ))
      ?>
      <meta charset="utf-8" content="text/html" />
      <meta name="description" content="made with love by arbib soufiane + helpp of bootstrap V3 ZF 2">
      <meta name="author" content="arbib soufine">
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
      <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDnLu5Azr7UlYeD2hhJlpHjSSsU_BX3Mx8"></script>
	  <!--[if lt IE 9]>
	        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	  <![endif]-->
</head>

<body style="background-color: #E0F2F1;">
	<!--/////////////////////////Body content///////////////////////////////-->

	<!-- petit progress bar qui s'affiche au cours de chargement du page 
	<div id="preloading">
		<br /> <br /> <br /> <br /> <br /> <br /> <br /> <br />
		<h1 class="center">Chargement...</h1>
		<div class="progress">
			<div class="indeterminate"></div>
		</div>
	</div>
    -->


	<!--affichage du menu si le système trouvé une session -->
<?php
// $session = new Container('admin');
// if ($session->offsetExists('email') && $session->offsetGet('user')=='admin'){
// $email = $session->offsetGet('email');
// $url_logout = $this->url('admin',array('action' => 'logout'));
// $url_index = $this->url('admin',array('action' => 'index'));

?> 


<span id="up"></span>
    <!--/////////////////////////Menu Dynamique///////////////////////////////-->
<nav class="navbar navbar-inverse" id="menu">

  <div class="container-fluid">
  
    <div class="navbar-header" id="phoneTabletBar">
      <!-- data-toggle="collapse"-->               
      <button type="button"class="navbar-toggle green-d3 btn-sm" data-toggle="collapse" data-target="#myNavbar">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>        
      </button>
      <a class="navbar-brand" href="index"> <img id="logoo" alt="LMPE LOGO" src="img/menuLogo.png"/>LMPE</a>
    </div><!--fin navbar header-->

    <div class="collapse navbar-collapse" id="myNavbar">
      <!--la premier list UL***********************-->
      <ul class="nav navbar-nav">
        <li class="active"><a href="index"><span class="glyphicon-home glyphicon"></span> Acueil</a></li>
        <li><a href="contact">Contact</a></li>
        <li><a href="#helpmodal" class="red-d2"  >Nos Aider</a></li>
        <li><a href="#aboutmodal">Apropos De Nous</a></li>
        <!--liste down drop-->
        <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Plus <span class="caret"></span></a>
        <ul class="dropdown-menu">
        <li><a href="lmpe_AllArticles">toutes les articles</a></li>
        </ul>
        </li><!-- fin liste down drop-->
      </ul><!--fin de la premier list UL et debut de la 2eme list UL-->

<!--  
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">'.$user.'<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li>
            <a href="Backend/actions/session/userlogout/logout.php">
              <span class="glyphicon glyphicon-log-out"></span> Deconnexion
            </a>
          </li>
        </ul>
      </li>-->
      <!--
      <li><a href="inscription"><span class="glyphicon glyphicon-user"></span> Inscription</a></li>
      <li><a href="login"><span class="glyphicon glyphicon-log-in"></span> Connecxion</a></li>
      -->


      <ul class="nav navbar-nav navbar-right">
        <li id="recherche_form">
          <div id="recherche" class="form-group-sm">
            <form role="form">       
              <input type="text" class="form-control" id="text_rech" />
              <button id="btn_rech" type="submit" class="btn btn-sm btn-success" />
                <span class="glyphicon glyphicon-search"></span>
              </button>
            </form>
          </div><!--fin recherche form-->            
        </li><!--fin de la liste recherche-->
      </ul><!--fin de la 2eme list UL-->     
    </div><!--fin de myNavbar-->
  </div><!--fin du fluid container-->             
</nav><!--fin nav--> 
	<!--//////////////////////////////////////////////////////////////////////-->



	<!--/////////////////////////Content///////////////////////////////-->
                   <?php echo $this->content; ?>
    <!--//////////////////////////////////////////////////////////////-->


	<!--/////////////////////////FOOTER ///////////////////////////////-->
<!--footer-->
<div class="w3-container" id="footer">
  <div id="band_newsletter">        
    <form role="form" method="post" action="Backend/actions/subscribe/SaveEmail.php">
        <div class="form-group-md">
           <h6 class="text-center text-info">inscrivez-vous pour recevoir nos nouvelles publications</h6>
           <div class="row">
             <label class="sr-only" for="email">address email:</label>
                <div class="col-sm-4"></div>
                <div class="col-sm-4">
                 <input type="email" required placeholder="Saisir Votre Email ici " class="form-control" id="email" name="email"/>
                 <br/>
                  <button type="submit" data-toggle="modal" class="btn btn-success btn-md">S'abonner</button>
                </div>           
                <div class="col-sm-4"></div>
            </div>          
         </div>
     </form>
   </div><!--fin de la band newsletter-->
                    
                    
                    
    <div class="row">
       <div class="col-lg-12">
         <div id="band_info">
                 <br/>
                 <p class="text-center" style="color:#FFF">
                   Ligue Marocaine pour la protection de l'enfance Marrakech
                 </p>
                 
                 <h6 class="text-center" style="color:#999">
                  Centre Commerciale d'Issil Lot. Agdal Marrakech ,Maroc
                 </h6>
                 
                 <h6 class="text-center" style="color:#FFF">
                 contact@lmpe-marrakech.com
                 </h6>
                 
                 <h6 class="text-center" style="color:#999">
                 +212 524 30 74 00
                 </h6>
                 
                 <h6 class="text-center" style="color:#999">
                 +212 661 17 74 63
                 </h6>
                 
                 <h6 class="text-center " style="color:#FFF">
                   suivez nous Sur les réseaux sociale <br/><br/>
                    <a href="#"><span ><img src="img/go.png" alt="socialeMediaIcons"></span>  </a>
                    <a href="#"><span ><img src="img/fb.png"  alt="socialeMediaIcons"></span>  </a>
                    <a href="#"><span ><img src="img/tw.png"  alt="socialeMediaIcons"></span>  </a>
                 </h6>
                 <br/>
                 <h6 class="text-center" id="up_btn">
                    <a href="#up"><img src="img/btn_down.png" alt="alez vres le hot"/></a>
                 </h6>                             
         </div><!--fin de la band_info -->      
       </div> <!--fin de col-->
    </div><!--fon du ligne (row)-->
  </div> 
 <!-- fin footer-->

            
            
            
            
            
            
<!--definition des modales content-->

  <!--modale (nous aider)-->
      <div class="w3-modal" id="helpmodal">
        <div class="w3-modal-dialog">
        <!-- Modal content-->
            <div class="w3-modal-content w3-card-1">
              <header class="w3-container green-d3"> 
                 <a href="#" class="w3-closebtn">&times;</a>
                 <h2>Aider les petites enfants</h2>
              </header>
              <div class="w3-container green-d1">
                <p class="text-center">
                   Vous pouvez effectuer un virement sur le compte bancaire de la ligue :<br/>
                    RIB: SWIFT <br/>
                    N°: BCMAMAMC -007 450 0000 00 030 7041238 65<br/>
                    Attijari Wafabank agence colisée- Marrakech
                </p>
              </div>
              <footer class="w3-container green-d3 ">
                 <p>LMPE MARRAKECH</p>
              </footer>
            </div>
        </div>             
      </div>
                 
  <!--modale (a propos de nous)-->
     <div class="w3-modal" id="aboutmodal" role="dialog">
       <div class="w3-modal-dialog">
       <!-- Modal content-->
          <div class="w3-modal-content">
             <header class="w3-container teal-d3"> 
                <a href="#" class="w3-closebtn">&times;</a>
                <h4 class="modal-title text-center">
                 <img src="img/logoC.png" alt="logo lmpe" class="img-responsive" style="margin:0 auto;"/>
                </h4>
              </header>
              <div class="w3-container teal-d1">
                 <p class="text-center">
                   La Ligue Marocaine pour la Protection de l'Enfance est une association reconnue d'utilité publique par                   dahir viziriel du 28 avril 1954. Le bureau régional de Marrakech a ouvert ses portes en 1987 et poursuit                   sa mission qui consiste à assurer la protection de l'enfance en situation précaire et particulièrement                   celle des enfants abandonnés.

                   L'activité principale de notre association est de prendre en charge dans les meilleures conditions                   possibles les bébés et enfants abandonnés (âgés de 1 jour à 5 ans) en attendant de leur trouver une                   famille kafile. (en savoir +). 32 nurses et 6 assistantes médicales se relaient pour assurer le suivi de                   nos enfants 24 sur 24 heures.
                 </p>
               </div>
               <footer class="w3-container teal-d3">
                 <p>LMPE MARRAKECH</p>
               </footer>
           </div>
         </div>
       </div>
              
   <!-- modale  (newsletter button_Push)-->
      <div class="container">
      <!-- Modal -->
        <div class="w3-modal" id="sub" role="dialog">
            <div class="w3-modal-dialog">
            <!-- Modal content-->
              <div class="w3-modal-content">
                  <header class="w3-container teal-d3"> 
                     <a href="#" class="w3-closebtn">&times;</a>
                     <h2>LMPE Newsletter</h2>
                  </header>
                  <div class="w3-container teal-d1">
                      <p>Merci pour votre inscription.</p>
                  </div>
                  <footer class="w3-container teal-d3">
                       <p class="text-center">LMPE</p>
                  </footer>
               </div>
             </div>
         </div>
      </div>
	<!--//////////////////////////////////////////////////////////////////////-->



	<!--/////////////////////////Scripts///////////////////////////////-->
		<script>
			(function() {

				var overlay = document.getElementById( 'overlay' ),
					overlayClose = overlay.querySelector( 'button' ),
					header = document.getElementById( 'header' )
					switchBtnn = header.querySelector( 'button.slider-switch' ),
					toggleBtnn = function() {
						if( slideshow.isFullscreen ) {
							classie.add( switchBtnn, 'view-maxi' );
						}
						else {
							classie.remove( switchBtnn, 'view-maxi' );
						}
					},
					toggleCtrls = function() {
						if( !slideshow.isContent ) {
							classie.add( header, 'hide' );
						}
					},
					toggleCompleteCtrls = function() {
						if( !slideshow.isContent ) {
							classie.remove( header, 'hide' );
						}
					},
					slideshow = new DragSlideshow( document.getElementById( 'slideshow' ), { 
						// toggle between fullscreen and minimized slideshow
						onToggle : toggleBtnn,
						// toggle the main image and the content view
						onToggleContent : toggleCtrls,
						// toggle the main image and the content view (triggered after the animation ends)
						onToggleContentComplete : toggleCompleteCtrls
					}),
					toggleSlideshow = function() {
						slideshow.toggle();
						toggleBtnn();
					},
					closeOverlay = function() {
						classie.add( overlay, 'hide' );
					};

				// toggle between fullscreen and small slideshow
				switchBtnn.addEventListener( 'click', toggleSlideshow );
				// close overlay
				overlayClose.addEventListener( 'click', closeOverlay );

			}());
		</script>
	<!--/////////////////////////Scripts///////////////////////////////-->
</body>

</html>
