<?php 
use Zend\Session\Container;
echo $this->doctype(); 
?>
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8"    content="text/html"/>
      <meta name="description" content="made with love by arbib soufiane + helpp of bootstrap V3 Framework">
      <meta name="author" content="arbib soufine">
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
      <meta http-equiv="Content-type" content="text/html; charset=UTF-8">

      <!--google maps scripts
      <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDnLu5Azr7UlYeD2hhJlpHjSSsU_BX3Mx8"></script>
      <script src="Backend/css-js/googlemaps.js" type="text/javascript"></script>
      -->

      <?php echo $this->headTitle('bdma')->setSeparator(' - ')->setAutoEscape(false) ?>
      <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>
 
      <?php
          echo $this->headLink()
          ->prependStylesheet($this->basePath('css/style.css'))
          ->prependStylesheet($this->basePath('w3/w3.css'))
          ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
      ?>

      <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
  </head>

<body data-spy="scroll" data-target=".navbar" data-offset="50" >
  <div id="visitor_counter">
    <p style="color:black;font-weight: bolder;">157 000 visiteur</p>
  </div>

  <span id="up"></span>

  <!--///////SLIDER///////-->
  <div class="container-fluid">
    <div id="myCarousel" class="carousel slide w3-card-8" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">

        <div class="item active">
          <img src="sl/1.jpg" alt="Chania" width="460" height="345">
          <div class="carousel-caption">
            <h3>Chania</h3>
            <p>The atmosphere in Chania has a touch of Florence and Venice.</p>
          </div>
        </div>

        <div class="item">
          <img src="sl/2.jpg" alt="Chania" width="460" height="345">
          <div class="carousel-caption">
            <h3>Chania</h3>
            <p>The atmosphere in Chania has a touch of Florence and Venice.</p>
          </div>
        </div>
      
        <div class="item">
          <img src="sl/3.jpg" alt="Flower" width="460" height="345">
          <div class="carousel-caption">
            <h3>Flowers</h3>
            <p>Beatiful flowers in Kolymbari, Crete.</p>
          </div>
        </div>

        <div class="item">
          <img src="sl/4.jpg" alt="Flower" width="460" height="345">
          <div class="carousel-caption">
            <h3>Flowers</h3>
            <p>Beatiful flowers in Kolymbari, Crete.</p>
          </div>
        </div>
    
      </div>

      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  <!--//////////////////////////////////////FINSLIDER///////////////////////////////////////////////////-->
</div>

<!--//////////// NAV BAR /////////////-->
<nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="420" id="menu">
  <div class="container-fluid">
    <div class="navbar-header" id="phoneTabletBar">
      <!-- data-toggle="collapse"-->               
      <button type="button"class="navbar-toggle green-d3 btn-sm" data-toggle="collapse" data-target="#myNavbar">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>        
      </button>
      <a  class="navbar-brand" href="/"> <img id="logoo" alt="LMPE LOGO" src="img/menuLogo.png"/>LMPE</a>
    </div><!--fin navbar header-->
    <div class="collapse navbar-collapse" id="myNavbar">
      <!--la premier list UL***********************-->
      <ul class="nav navbar-nav">
        <li class="active"><a href="/"><span class="glyphicon-home glyphicon"></span> Acueil</a></li>
        <li><a href="/contact">Contact</a></li>
        <li><a href="#helpmodal" class="red-d2">Nos Aider</a></li>
        
        <!--liste down drop-->
        <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#aboutmodal"><span class="glyphicon glyphicon-question-sign"></span> Apropos De Nous</a></li>
          <li><a href="/view_all_articles"><span class="glyphicon glyphicon-globe"></span> Toutes les articles</a></li>
          <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Se connecté</a></li>
          <li>
            <a href="/signup">
              <span class="glyphicon glyphicon-plus-sign"></span> 
              <span class="glyphicon glyphicon-user"></span>
              S'inscrire
            </a>
          </li>
        </ul>




        </li><!-- fin liste down drop-->
      </ul><!--fin de la premier list UL et debut de la 2eme list UL-->
      <ul class="nav navbar-nav navbar-right">
        <li id="recherche_form">
        <div id="recherche" class="form-group-sm">
          <form role="form">       
            <input type="text" class="form-control" id="text_rech">
            <button id="btn_rech" type="submit" class="btn btn-sm btn-success">
              <span class="glyphicon glyphicon-search"></span>
            </button>
          </form>
        </div><!--fin recherche form-->            
        </li><!--fin de la liste recherche-->
      </ul><!--fin de la 2eme list UL-->     
    </div><!--fin de myNavbar-->
  </div><!--fin du fluid container-->             
</nav><!--fin nav--> 
<!--///////////////////////////////FIn NAV BARs///////////////////////////////////////////////////////////////////-->




    <!--/////////////////////////Content///////////////////////////////-->
    <div id="fetched_content">
        <?php echo $this->content; ?>          
    </div>

    <!--/////////////////////////Content///////////////////////////////-->




<!--///////////////////////// FOOTER ///////////////////////////////-->

<!--footer-->
<div class="w3-container" id="footer">
  <div id="band_newsletter">   
<span id="subscription"></span>
    <form role="form" method="post" action="Backend/actions/subscribe/SaveEmail.php">
        <div class="form-group-md">
           <h6 class="text-center text-info">inscrivez-vous pour recevoir nos nouvelles publications</h6>
           <div class="row">
             <label class="sr-only" for="email">address email:</label>
                <div class="col-sm-4"></div>
                <div class="col-sm-4">
                  <?php 

                           if (isset($_GET['state']) && $_GET['state']=='saved')
                           {

                              echo "
                              <div class='alert alert-success'>
                                <a href='#'' class='close' data-dismiss='alert' aria-label='close'>&times;</a>
                                <strong>Operation terminé </strong> 
                              </div>


                               ";
                          } 
                          ?>
                 <input type="email" required placeholder="Saisir Votre Email ici " class="form-control" id="email" name="email"/>
                 <br/>
                  <button type="submit" data-toggle="modal" class="btn btn-success btn-md">S'abonner</button>
                </div>           
                <div class="col-sm-4"></div>
            </div>          
         </div>
     </form>
   </div><!--fin de la band newsletter--> 
    <div class="row">
       <div class="col-lg-12">
         <div id="band_info">
                 <br/>
                 <p class="text-center" style="color:#FFF">
                   Ligue Marocaine pour la protection de l'enfance Marrakech
                 </p>
                 
                 <h6 class="text-center" style="color:#999">
                  Centre Commerciale d'Issil Lot. Agdal Marrakech ,Maroc
                 </h6>
                 
                 <h6 class="text-center" style="color:#FFF">
                 contact@lmpe-marrakech.com
                 </h6>
                 
                 <h6 class="text-center" style="color:#999">
                 +212 524 30 74 00
                 </h6>
                 
                 <h6 class="text-center" style="color:#999">
                 +212 661 17 74 63
                 </h6>
                 
                 <h6 class="text-center " style="color:#FFF">
                   suivez nous Sur les réseaux sociale <br/><br/>
                    <a href="#"><span ><img src="img/go.png" alt="socialeMediaIcons"></span>  </a>
                    <a href="#"><span ><img src="img/fb.png" alt="socialeMediaIcons"></span>  </a>
                    <a href="#"><span ><img src="img/tw.png" alt="socialeMediaIcons"></span>  </a>
                 </h6>
                 <br/>
                 <h6 class="text-center" id="up_btn">
                    <a href="#up"><img src="img/btn_down.png" alt="alez vres le hot"/></a>
                 </h6>                             
         </div><!--fin de la band_info -->      
       </div> <!--fin de col-->
    </div><!--fon du ligne (row)-->
  </div> 
 <!-- fin footer-->  


<!--definition des modales content//////////////////////////////////////////////////////////////////////////////////-->
  <!--modale (nous aider)-->
      <div class="w3-modal" id="helpmodal">
        <div class="w3-modal-dialog">
        <!-- Modal content-->
            <div class="w3-modal-content w3-card-1">
              <header class="w3-container green-d3"> 
                 <a href="#" class="w3-closebtn">&times;</a>
                 <h2>Aider les petites enfants</h2>
              </header>
              <div class="w3-container green-d1">
                <p class="text-center">
                   Vous pouvez effectuer un virement sur le compte bancaire de la ligue :<br/>
                    RIB: SWIFT <br/>
                    N°: BCMAMAMC -007 450 0000 00 030 7041238 65<br/>
                    Attijari Wafabank agence colisée- Marrakech
                </p>
              </div>
              <footer class="w3-container green-d3 ">
                 <p>LMPE MARRAKECH</p>
              </footer>
            </div>
        </div>             
      </div>
                 
  <!--modale (a propos de nous)-->
     <div class="w3-modal" id="aboutmodal" role="dialog">
       <div class="w3-modal-dialog">
       <!-- Modal content-->
          <div class="w3-modal-content">
             <header class="w3-container teal-d3"> 
                <a href="#" class="w3-closebtn">&times;</a>
                <h4 class="modal-title text-center">
                 <img src="img/logoC.png" alt="logo lmpe" class="img-responsive" style="margin:0 auto;"/>
                </h4>
              </header>
              <div class="w3-container teal-d1">
                 <p class="text-center">
                   La Ligue Marocaine pour la Protection de l'Enfance est une association reconnue d'utilité publique par                   dahir viziriel du 28 avril 1954. Le bureau régional de Marrakech a ouvert ses portes en 1987 et poursuit                   sa mission qui consiste à assurer la protection de l'enfance en situation précaire et particulièrement                   celle des enfants abandonnés.

                   L'activité principale de notre association est de prendre en charge dans les meilleures conditions                   possibles les bébés et enfants abandonnés (âgés de 1 jour à 5 ans) en attendant de leur trouver une                   famille kafile. (en savoir +). 32 nurses et 6 assistantes médicales se relaient pour assurer le suivi de                   nos enfants 24 sur 24 heures.
                 </p>
               </div>
               <footer class="w3-container teal-d3">
                 <p>LMPE MARRAKECH</p>
               </footer>
           </div>
         </div>
       </div>
<!--fin modals ///////////////////////////////////////////////////////////////////////////////////////////////////////////////-->            


    <!--//////////////////////////// SCRIPT FILES ////////////////////////////////-->
   
      <?php  echo $this->headScript()->prependFile($this->basePath('js/jquery.min.js'));?>
      <?php  echo $this->headScript()->prependFile($this->basePath('js/bootstrap.min.js'));?>
      <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.0.6/jquery.mousewheel.min.js" type="text/javascript" charset="utf-8"></script>
      <?php  #echo $this->headScript()->prependFile($this->basePath('js/jquery.mousewheel.min.js'));?>
      <?php  #echo $this->headScript()->prependFile($this->basePath('js/jquery.simplr.smoothscroll.js'));?>
      <script src="js/jquery.simplr.smoothscroll.js" type="text/javascript" charset="utf-8"></script>
    <!--////////////////////////////////////////////////////////--> 







    <!--/////////////////////////// JS & JQ Functions /////////////////////////////--> 

            <script  type="text/javascript" charset="utf-8" >
                $(document).ready(function() { 
                });
            </script>

            <script type="text/javascript">
                $(function () {
                  $.srSmoothscroll({
                    // defaults
                    step: 55,
                    speed: 400,
                    ease: 'swing',
                    target: $('body'),
                    container: $(window)
                  })
                });


                $("h6 a[href^='#']").on('click', function(e) {
                 // prevent default anchor click behavior
                 e.preventDefault();

                 // store hash
                 var hash = this.hash;

                 // animate
                 $('html, body').animate({
                     scrollTop: $(hash).offset().top
                   }, 300, function(){

                     // when done, add hash to url
                     // (default click behaviour)
                     window.location.hash = hash;
                   });

              });
            </script>

    <!--/////////////////////////Scripts///////////////////////////////--> 
</body>

</html>
